import java.time.LocalDateTime;

/**
 * Represents a system user in the contact management application.
 * <p>
 * A user has login credentials (username, hashed password, salt),
 * personal identification fields (name, surname), a system role
 * ({@link Role}), and a creation timestamp used for auditing.
 */
public class User
{
    /** Unique identifier for the user (auto-generated by the database). */
    private int userId;

    /** The username used for login authentication. */
    private String username;

    /** The hashed password generated via PBKDF2. */
    private String passwordHash;

    /** The cryptographic salt used when hashing the password. */
    private String passwordSalt;

    /** First name of the user. */
    private String name;

    /** Surname (last name) of the user. */
    private String surname;

    /** Role defining the user's permissions in the system. */
    private Role role;

    /** Timestamp marking when the user account was created. */
    private LocalDateTime createdAt;


    /**
     * Returns the unique ID of the user.
     *
     * @return user ID
     */
    public int getUserId()
    {
        return userId;
    }

    /**
     * Sets the user's unique ID.
     *
     * @param userId the ID to assign
     */
    public void setUserId(int userId)
    {
        this.userId = userId;
    }

    /**
     * Returns the username used for logging in.
     *
     * @return username
     */
    public String getUsername()
    {
        return username;
    }

    /**
     * Sets the username for the account.
     *
     * @param username new username
     */
    public void setUsername(String username)
    {
        this.username = username;
    }

    /**
     * Returns the stored PBKDF2 password hash.
     *
     * @return password hash
     */
    public String getPasswordHash()
    {
        return passwordHash;
    }

    /**
     * Sets the hashed password for this user.
     *
     * @param passwordHash PBKDF2-generated hash
     */
    public void setPasswordHash(String passwordHash)
    {
        this.passwordHash = passwordHash;
    }

    /**
     * Returns the cryptographic salt used when hashing the password.
     *
     * @return Base64-encoded salt
     */
    public String getPasswordSalt()
    {
        return passwordSalt;
    }

    /**
     * Sets the salt used for password hashing.
     *
     * @param passwordSalt Base64-encoded salt string
     */
    public void setPasswordSalt(String passwordSalt)
    {
        this.passwordSalt = passwordSalt;
    }

    /**
     * Returns the first name of the user.
     *
     * @return user’s first name
     */
    public String getName()
    {
        return name;
    }

    /**
     * Sets the first name of the user.
     *
     * @param name new first name
     */
    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * Returns the user's surname.
     *
     * @return surname
     */
    public String getSurname()
    {
        return surname;
    }

    /**
     * Sets the user's surname.
     *
     * @param surname new surname
     */
    public void setSurname(String surname)
    {
        this.surname = surname;
    }

    /**
     * Returns the system role determining this user's permissions.
     *
     * @return role of the user
     */
    public Role getRole()
    {
        return role;
    }

    /**
     * Sets the user's role.
     *
     * @param role role to assign
     */
    public void setRole(Role role)
    {
        this.role = role;
    }

    /**
     * Returns the timestamp of when this user account was created.
     *
     * @return creation time
     */
    public LocalDateTime getCreatedAt()
    {
        return createdAt;
    }

    /**
     * Sets the account creation timestamp.
     *
     * @param createdAt a LocalDateTime representing the creation moment
     */
    public void setCreatedAt(LocalDateTime createdAt)
    {
        this.createdAt = createdAt;
    }

    /**
     * Returns a simplified string representation of the user,
     * excluding security-sensitive fields such as password hash
     * and salt.
     *
     * @return readable user summary
     */
    @Override
    public String toString()
    {
        return "User{"
            + "userId=" + userId
            + ", username='" + username + '\''
            + ", name='" + name + '\''
            + ", surname='" + surname + '\''
            + ", role=" + role
            + '}';
    }
}
